on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build mvn
        working-directory: department-service
        run: |
          mvn clean package -DskipTests

      - name: Build and tag Docker image
        working-directory: department-service
        run: |
          docker build -t department-service:v1 .


  deploy:
    env:
      APP_PORT: ${{ secrets.APP_PORT }}
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    runs-on: [self-hosted]
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Stop and Remove Existing Containers
        working-directory: department-service
        run: docker compose down || true  # Ignore errors if no containers are running

      - name: Run with Docker Compose
        working-directory: department-service
        run: docker compose up -d
